title: Playa de las Catedrales
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://ascatedrais.xunta.gal/monatr/inicio?lang=es
