title: Playa de las Catedrales
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

logo: logo.jpeg

favicon_ico: "/assets/images/favicon.ico"


nav_external_links:
  - title: Solicitud Ticket Acceso
    url: https://ascatedrais.xunta.gal/monatr/inicio?lang=es
    hide_icon: false
    opens_in_new_tab: false
 
