title: Playa de las Catedrales
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io


logo: "(!https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.galiciatravels.com%2F6-datos-sobre-la-playa-de-las-catedrales%2F&psig=AOvVaw1peX7oVrgG6HY8L9ZM2b4X&ust=1729591192405000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLjkwrabn4kDFQAAAAAdAAAAABAE)"

nav_external_links:
  - title: Solicitud Ticket Acceso
    url: https://ascatedrais.xunta.gal/monatr/inicio?lang=es
    hide_icon: false
    opens_in_new_tab: false
 
